language: node_js
node_js:
- 6
- 7
- 8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/117063f9c1031b17e557
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: hello@mylisabox.com
  api_key:
    secure: Yz9cMH3Bl2XRwT8nWW6AnK/0Y4c5rBHW0AnNiVloc892bgugf/eMGacoBq5qYF31gJtpr8QQj9ynWZ7zhlW2xHmINQFX0AtGSpZ5pDfyfIv+ijGKuT8cv8Ml6lJ/tjNJ49TB/SL5kfI9qf5d9XbCwHVQivzZUnoLKDTQj5hzFTX/DeioEeLURnilkuZ8u4bcNe04T0aLJfQJ1vmgGGX9WXvlHuXywilzryjhoW0M7mTfdw53nnckoN5huA7mo5ddBYEPMLu4FS+aiPPXrASX679HbzrwguBrfOZF1VfzfwchDse9qVAps8OG6/M1jmUZgVmvORwxJQqNvCE7WeEWACCwe9G0GvfHhoED+zvVCQSzAQOaF8BihT0DuzmRGSEDXgNaGWCXLdtEDfj4+DO0JnkXBb5mkduWvM3hcQqiU8nqs4RVUa1vXwuzuOzEsB1SMOBAwGlLSO+LzVs+cO0NSBrPTlL/M3PIPr3zNI4uz5U8d1VVfgyVEPiRt7KteAb5QAFHZL5l3cdHfFKKR1s8IG/8DP04T77kvh2FRYItqCy5b+qEFJ6J73yuzenvPmDjnZNgnDPZHxT7XNZmwy6nTQlJdnNZkcBJr9a7jtc1dJqirqvwowh/GpbnDsWf+QD80vYW5nkNpfBcm7ihsolywvqcCONzxuhTGWv66UlaoDI=
  on:
    tags: true
    repo: mylisabox/lisa-standalone-voice-command
    node: 7
